___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
array = np.zeros(10)

#### Create an array of 10 ones

In [5]:
array = np.ones(10)

#### Create an array of 10 fives

In [11]:
array = np.ones(10)*5

#### Create an array of the integers from 10 to 50

In [15]:
array = np.arange(10,50)

#### Create an array of all the even integers from 10 to 50

In [17]:
array = np.arange(10,2,50)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
array = np.arange(0,9).reshape(3,3)

#### Create a 3x3 identity matrix

In [23]:
array_2D = np.identity(3)

#### Use NumPy to generate a random number between 0 and 1

In [31]:
array = np.random.rand(0,1)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [33]:
random_array = np.random.randn(25)

#### Create the following matrix:

In [35]:
array = np.array

#### Create an array of 20 linearly spaced points between 0 and 1:

In [5]:
[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
 0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
 0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
 0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]


[0.0,
 0.05263158,
 0.10526316,
 0.15789474,
 0.21052632,
 0.26315789,
 0.31578947,
 0.36842105,
 0.42105263,
 0.47368421,
 0.52631579,
 0.57894737,
 0.63157895,
 0.68421053,
 0.73684211,
 0.78947368,
 0.84210526,
 0.89473684,
 0.94736842,
 1.0]

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [9]:
mat = np.arange(1,26).reshape(5,5)

NameError: name 'np' is not defined

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!