In [22]:
import numpy as np
S = np.random.randn(5,5)
R = np.random.randn(5,2)

#identity
I = np.eye(3)
print(I) 

print('')

#Zeros
Z = np.zeros((4,4))
print(Z)

print('')

#DIAGONAL
D = np.diag([1,2,3,4,5,9])
print(D)

print('')
#Tingular
X = np.random.randn(5,5)
U = np.triu(X)
L = np.tril(X)
print(U)
print('')
print(L)

#Concatenate
A = np.random.randn(3,2)
B = np.random.randn(4,4)
C = np.concatenate(A,B)
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 9]]

[[ 0.20446977 -0.50247705  1.81491161  0.25545302 -0.39813664]
 [ 0.         -1.67099085  0.82405458 -1.84833481 -0.0450456 ]
 [ 0.          0.         -0.61287121 -0.07315597 -1.83549491]
 [ 0.          0.          0.         -1.73449566  0.38615724]
 [ 0.          0.          0.          0.          0.67973671]]

[[ 0.20446977  0.          0.          0.          0.        ]
 [ 0.11192609 -1.67099085  0.          0.          0.        ]
 [ 0.64166226 -0.74825896 -0.61287121  0.          0.        ]
 [ 0.39302602  1.21933227  0.87938031 -1.73449566  0.        ]
 [-0.25209336  1.40113437  0.30919906 -1.80767816  0.67973671]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [6]:
import numpy as np
M = np.round(8*np.random.rand(4,4))

d = np.diag(M)
D = np.diag(d)
print(M),print('')
print(d),print('')
print(D),print('')

X = np.trace(M)
Y = sum(d)
print(X ),print('')
print(Y), 

[[1. 1. 6. 2.]
 [2. 1. 6. 4.]
 [1. 4. 5. 5.]
 [4. 2. 5. 7.]]

[1. 1. 5. 7.]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 7.]]

14.0

14.0


(None,)

In [28]:
import numpy as np

#Nomor 1
l = 7
A = np.round(5*np.random.randn(3,3))
B = np.round(5*np.random.randn(3,3))
print(A),print('')
print(B),print('')
#trace
Tr1 = np.trace(A)
Tr2 = np.trace(B)
S1 = Tr1 + Tr2
S2 = np.trace(A + B)
print(S1,) ,
print(S2,"\n")

#nomor 2 


Sk1 = np.trace(l * A)
Sk2 = l*np.trace(A)
print(Sk1)
print(Sk2)

[[-1.  1. -1.]
 [ 1. -0.  5.]
 [-6.  6.  7.]]

[[-3. -2. -1.]
 [ 4. -6. -3.]
 [ 7.  6. -5.]]

-8.0
-8.0 

42.0
42.0
